apiVersion: v1
kind: Service
metadata:
  name: basset-app-service
  labels:
    app: basset-app
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: basset-app
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: basset-app-ingress
spec:
  backend:
    serviceName: basset-app-service
    servicePort: 80